Update php.yml
Signed-off-by: ArchBlood <35392110+ArchBlood@users.noreply.github.com>

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -18,7 +18,13 @@ jobs:
     - uses: actions/checkout@v3
 
     - name: Validate composer.json and composer.lock
-      run: composer validate --strict
+      run: |
+        composer validate --strict
+        VALIDATE_STATUS=$?
+        if [ $VALIDATE_STATUS -ne 0 ]; then
+          echo "Composer validation failed. Running composer update."
+          composer update
+        fi
 
     - name: Cache Composer packages
       id: composer-cache
